### ISSUE TITLE
Do not combine list tabs into single one in the mobile theme

### ISSUE THREAD

**Issue by lsmanrique** [maxpozdeev/mytinytodo#102]
Hello there, I love the graceful way in which the tasks are seen on the mobile phone. But in the past I was used to seeing all the to-do lists (the tabs) in several rows. In the latest versions there is an icon where all todo lists are contained. Is there a variable somewhere where I could revert to all tabs being visible? (Or a view mode I could add to the URL)?

**Comment by maxpozdeev** [comment]
Please try to remove or comment the line 1368 in content/theme/style.css with content `li.mtt-tab { display:none; }` (next after singletab comment). 
Is that you look for?

**Comment by lsmanrique** [comment]
Yes, this was exactly it, thanks a lot. This tool keeps being the simplest and cleanest interface I have seen. I keep finding uses for it (public URL bookmarks in this case). Ideally task names would allow <a href="http://www.sampleurl.com" target="_blank">tap here</a>  or its equivalent in markdown but for now a task named. "tap here http://www.sampleurl.com" also does it well.

Thanks for your gift to all of us with Mytinytodo, all the best for the New Year!

**Comment by maxpozdeev** [comment]
I do not plan to add any text formatting for a task title. I dont like this idea, sorry.
Best wishes in the new year!

**Comment by maxpozdeev** [comment]
In Custom CSS extension this can be done by adding
```
li.mtt-tab:not(.mtt-tab-hidden) {
  display:unset;
}
```

> Please try to remove or comment the line 1368 in content/theme/style.css with content `li.mtt-tab { display:none; }` (next after singletab comment). Is that you look for?

**Comment by lsmanrique** [comment]
Thanks for this, will give it a try next weekend and add a reply here.

**Comment by lsmanrique** [comment]
Tried it, still in version 1.7.3 but already CSS extension there. The line to comment (after the addition in the custom CSS extension) in that version is content/theme/style.css 1094  /* li.mtt-tab { display:none; } */

Thanks a lot!!

**Comment by maxpozdeev** [comment]
If you use CSS extension you dont need to edit style.css, even on every app update.
