### ISSUE TITLE
Why are URLs not displayed as links anymore in task title?

### ISSUE THREAD

**Issue by qwertfisch** [maxpozdeev/mytinytodo#12]
Since version 1.7 (which is WIP) the task title does not parse and display URLs as clickable links anymore. In the task note itself, URLs are still clickable.

The change was introduced in f035fa3 without further explanation to why this is. It only states:
 > do not allow urls and any html elements in task title (escape all)

I can understand that the formatting is moved from JavaScript to PHP side, but what is the reason behind not formatting URLs in the title? This should not be out of any security reasons, nor is this difficult to process the text the same way as with the task note. Having close to zero knowledge about PHP, I did a working (but possibly hacky?) solution for this in a three-line patch (see [urls-in-title.txt](https://github.com/maxpozdeev/mytinytodo/files/6718947/urls-in-title.txt)). It also removes the unnecessary `dehtml()` function that creates some edge case errors.

As my workflow consists of putting quick URLs as one-liners in MTT as kind of bookmark-keeping, this feature is a must-have. It would be great to get this back, or at least a quick reasoning about why the feature was removed and should stay so.

**Comment by maxpozdeev** [comment]
v1.7 is still "under construction" and this is a temporary solution. Clickable URLs in titles will come back. No ETA.
Main goal of v1.7 is to add Markdown support in notes.

**Comment by qwertfisch** [comment]
Thanks for the clarification. I will stick around for 1.6.x then.

Also a big thank you for resuming development after so many years. I am using MTT for about ten years and really like the design refresh.
