### ISSUE TITLE
Ability to make 'All tasks' tab permanent

### ISSUE THREAD

**Issue by Sonof8Bits** [maxpozdeev/mytinytodo#16]
This is a feature request or enhancement.

I work with MTT daily and use all tasks to see the due dates of everything in order. Having to click menu -> all tasks -> sort by due date isn't that much work of course, but it would be really nice if I could just have the all tasks tab enabled by default. And it would be great if it remembered how I want it sorted just like any other list tab (sort by hand is missing for this reason I guess?).

**Comment by maxpozdeev** [comment]
Implemented in c9282c7 and b657cc4. Will be published in v1.7.

**Comment by Sonof8Bits** [comment]
Great! Thank you!
