### ISSUE TITLE
Choose between delete or cross out an achieved task

### ISSUE THREAD

**Issue by Go-rom** [maxpozdeev/mytinytodo#22]
Hello,

right now, when we tick a checkbox related to a task, the task is deleted.
Would be great to get an option which crosses out an achieved task instead of deleting it, ~~like this~~

Thank you !

**Comment by maxpozdeev** [comment]
It is not deleted. Please read - https://mytinytodo.net/faq.php#compltasks

**Comment by Go-rom** [comment]
All right, sorry for this useless ticket.
Now i'm aware of your website, thank you.
