### ISSUE TITLE
Ability to Set Default Sort Order

### ISSUE THREAD

**Issue by xenotropic** [maxpozdeev/mytinytodo#24]
Whenever one reloads the page, the default sort order is the order tasks were created in. One can of course change it each time but it would be nice if either sort order was "sticky" (kept the last sort chosen even on page reload), or if it could be set in preferences.

**Comment by maxpozdeev** [comment]
You mean the tab will "all tasks"?

**Comment by xenotropic** [comment]
Correct. (Although it would be nice if sorting could apply to particular lists also, didn't realize that didn't exist currently).

**Comment by maxpozdeev** [comment]
The 'all tasks' tab will remember the order in the next version - v1.7 (already implemented, but not ready to be released).

Every list remembers its individual sorting order between page reloads. This does not work for you?

**Comment by xenotropic** [comment]
Ah, yes it does. I just hadn't seen the drop-down arrow on each particular list to set it. Thanks!
