### ISSUE TITLE
"Not installed. Run setup.php first." when running setup.php

### ISSUE THREAD

**Issue by objecttothis** [maxpozdeev/mytinytodo#27]
I am updating an old 1.4.3 install to 1.6.8.

Instructions at https://www.mytinytodo.net/faq.php#update say 

1.    Download, unpack and replace all files excluding directory 'db'.
2.    Run 'setup.php' and upgrade database if required. 

I renamed my root directory, then created a new directory and copied config.php and todolist.db from the old install to the new.  This is a MySQLi database. When I attempt step 2 above I get the message Not installed. Run setup.php first. 

I've double-checked the config file against the 1.6.8 default config file.  The only change was needing to add the [detectmobile] array value.  I've checked file permissions.  Directories are 755 and files are 644.  

Ideas?

**Comment by objecttothis** [comment]
I've also attempted to copy files from 1.6.8 (minus /db/*) and overwrite the ones in the existing install, but that yields the same result.

**Comment by maxpozdeev** [comment]
Possible reasons:
1. db/config.php is not found or not readable (should be an errors in error log)
2.  Line with ```$config['db'] = 'mysql'; ``` is not present in db/config.php

**Comment by maxpozdeev** [comment]
As a step to find a reason, please try to rename db/config.php to something like config.bak and run mytinytodo.
There should be an error on require() call. 
If error is preset - access rights are good and config is on right place. Then rename file back to config.php

**Comment by objecttothis** [comment]
> As a step to find a reason, please try to rename db/config.php to something like config.bak and run mytinytodo. There should be an error on require() call. If error is present - access rights are good and config is on right place. Then rename file back to config.php

Thanks for the help here.  I figured out the problem.  Back when mysql drivers got deprecated in favor of mysqli, I had to to modify the code in 1.4.3 to accept mysqli drivers, so I renamed this array value to mysqli in my config file.  As soon as I changed it to mysql, it loaded the application.

However, now the settings and login links are unresponsive at the top of the page.  I tried it in both firefox and edge.  It appears to not like something in your javascript... missing empty quotes maybe?

![image](https://user-images.githubusercontent.com/17935339/163532815-f73fd9f2-f2ab-4092-908f-db9e0e1f3860.png)

**Comment by maxpozdeev** [comment]
> It appears to not like something in your javascript... missing empty quotes maybe?

Seems like a bug.
Please show that you set for ```$config['title']``` in db/config.php, as well as PHP version.

**Comment by objecttothis** [comment]
Figured it out.  The 1.4.3 version of the config file was ANSI (Codepage 1252) and the title was not in the ANSI characterset.  I had to save the file encoding of config.php as UTF-8 and then it worked. The upgrade is complete and it works now.  Here are my recommendations:
- Modify the Update to new Version section of your FAQ to encourage anyone upgrading from 1.4.3 or older to make sure that the encoding of the config.php is UTF-8 or to just copy the values over to the new template... this is also important because the older versions of the config did not have a "detectmobile" array key, so they will miss that value if they just "Download, unpack and replace all files excluding directory 'db'"
- It's not a big deal, but your `$config['db'] = 'mysql';` is actually using the MySQLi driver since the older MySQL driver has been deprecated and removed. It would be more consistent to make this value 'mysqli'.  That said, no one except those (like me) who modified the older code to accept MySQLi and happened to change that will care or notice, so take it with a grain of salt.

**Comment by maxpozdeev** [comment]
> The 1.4.3 version of the config file was ANSI (Codepage 1252) and the title was not in the ANSI characterset.

This is strange. mytinytodo used utf-8 encoding from the beginning. 

>  older versions of the config did not have a "detectmobile" array key, so they will miss that value if they just "Download, unpack and replace all files excluding directory 'db'"

Missing settings in config file will not produce errors, default values are used.



>  but your `$config['db'] = 'mysql';` is actually using the MySQLi driver since the older MySQL driver has been deprecated and removed.

This parameter is not about drivers, but database type in use.
