### ISSUE TITLE
About v1.7

### ISSUE THREAD

**Issue by lsmanrique** [maxpozdeev/mytinytodo#32]
Good afternoon,

You mentioned that markdown (some sort/flavour) would be available in version 1.7

Any idea of when it would be able to see the light? Any testing we could be helping with?

Br,

Luis

**Comment by maxpozdeev** [comment]
Version 1.7 beta (for tests and feedback) will be published soon this week, maybe tomorrow. It's mostly ready.

**Comment by lsmanrique** [comment]
Thanks a lot Max.
