### ISSUE TITLE
Authentication fails in v1.7-beta

### ISSUE THREAD

**Issue by sparkles6452** [maxpozdeev/mytinytodo#38]
Been playing around with 2022-08-18: v1.7-beta 

Now, suddenly not possible to access the instance.

Password is rejected. Tried from both Windows and smartphone browser.

Upon login attempt, the following is stated in red in header:
Some error occurred (click for details)

In details, is states:
Access denied! You must authenticate first.

**Comment by sparkles6452** [comment]
Tries accessing it from different browser with no history of the instance.... Then password works. 

For browsers with previous history with the instance: authentication fails

**Comment by sparkles6452** [comment]
Fails in both Chrome and Firefox

**Comment by maxpozdeev** [comment]
This is a bug in session handling. Was fixed in 85dd42c. 
I will publish new release in one or two days with all fixes.
Or you can update your setup with attached one.
[mytinytodo-v1.7-nightly.tar.gz](https://github.com/maxpozdeev/mytinytodo/files/9690995/mytinytodo-v1.7-nightly.tar.gz)

**Comment by sparkles6452** [comment]
Thanks @maxpozdeev for a great piece of software 😊
