### ISSUE TITLE
Change defaulting to /#alltasks

### ISSUE THREAD

**Issue by lsmanrique** [maxpozdeev/mytinytodo#39]
Hi there,

(Not an issue per se likely) Version 1.7-beta seems to default to /#alltasks  I do not see where could we have it default to list 1 (or last used list). Is there a way to have it defaulting to other than #alltasks?

Thanks,

Luis.

**Comment by maxpozdeev** [comment]
Yes, this is really need to be changed.

As for now you can use a bookmark to the url with the list you want to see first.

**Comment by lsmanrique** [comment]
Will do that, thanks a lot for this beautiful artwork! A tool I use daily.
