### ISSUE TITLE
Unable to Sort by hand on Android.

### ISSUE THREAD

**Issue by DrSalmandelhi** [maxpozdeev/mytinytodo#43]
Retrieved Back

**Comment by DrSalmandelhi** [comment]
https://user-images.githubusercontent.com/116563201/197520680-601406ca-9c38-44c1-bdbd-4a1814416ef8.mp4

**Comment by maxpozdeev** [comment]
Android version and browser?

**Comment by DrSalmandelhi** [comment]
Android Version 11,  And All Browser Like Chrome, Firefox and Brave, Even In pc (chrome in developing mode) in Mobile view.

**Comment by maxpozdeev** [comment]
Can not confirm on Android 11, Android 12  and desktop mobile mode.
Did you change the code? I see you have green bold titles in the list.
Can you re-test on demo at https://mytinytodo.net/demo/ ?

**Comment by maxpozdeev** [comment]
Does this sorting work on desktop browser (not mobile mode)?

**Comment by DrSalmandelhi** [comment]
Yes...It work Really Good.

**Comment by DrSalmandelhi** [comment]
See. It doesn't work most of the time.

https://user-images.githubusercontent.com/116563201/197698701-1f5215fa-f15d-4c28-933a-f0e621c57b17.mp4

**Comment by maxpozdeev** [comment]
Thank you, seems I can repeat the issue. Will fix it asap.

**Comment by maxpozdeev** [comment]
Added a fix. Please test on demo at https://mytinytodo.net/demo/

**Comment by DrSalmandelhi** [comment]
Now Working Great. Tested In all Moble devices and in Desktop in mobile view.. 
This bug is Fully fixed... 
Great Job ..**working 100% **
