### ISSUE TITLE
Remember last opened list: If public lists then remembered one is the public list.

### ISSUE THREAD

**Issue by lsmanrique** [maxpozdeev/mytinytodo#47]
Hello there Max,

I have seen you made further enhancements with 1.7.2 from this summer´s beta, thanks so much. I have updated my lists.

However I see that if you have a public list (I have one where I keep direct links to be shared (radios), then the remembered list is always this public one, regardless of the last one you were on before logout.   I would say that if possible remembering the last list would be more useful than the public one (but maybe this was by design, or there is no other way to implement it if Public lists are present).

Best regards, Luis.

**Comment by maxpozdeev** [comment]
Probably the idea to remember the last used lists is not so good, considering to make it optional or even remove.

**Comment by maxpozdeev** [comment]
Released in v1.7.3

**Comment by lsmanrique** [comment]
Saw it in the changelog and updated <https://t.manrique.com> it on 3 sets I
have, thank you very much.
