### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by r7l** [maxpozdeev/mytinytodo#48]
While the default theme is ok and well thought, it would be great if it would be possible to extend the default theme with a custom CSS file.

As a suggestion, you could simply add a single input field to settings page where you could specify the location to the custom CSS file. This file should then be included right after your CSS and make it possible to override the styles as it pleases.

**Comment by maxpozdeev** [comment]
Implemented as extension in 01e688b49ebecb7876d4e9db03e6cbcd832d64c4
Will be released in 1.7.3

**Comment by r7l** [comment]
That's awesome. Thanks allot!

**Comment by maxpozdeev** [comment]
v1.7.3 was published. 
You have to active extension to use it.  Unpack archive in ext directory and go to settings to enable.
