### ISSUE TITLE
Questions about the translation file `cns.json`

### ISSUE THREAD

**Issue by xhemj** [maxpozdeev/mytinytodo#55]
When translating the Simplified Chinese language #54 , I found that the file name for the Simplified Chinese translation is `cns.json`, perhaps it would be better to use the generic file name `zh-cn.json` , just like the Traditional Chinese file name `zh-tw.json`.

Also, according to Wikipedia, the three-letter abbreviation of  `cns`  is not Simplified Chinese, not even Chinese: https://en.wikipedia.org/wiki/ISO_639:cns .

**Comment by maxpozdeev** [comment]
Yes, you are right. Will rename it.
In 2009 I used `cn` and `cns` codes for Chinese languages. Later traditional one was renamed on translation update, but `cns` was untouched.
