### ISSUE TITLE
Updating a language pack, but I'm not the original author

### ISSUE THREAD

**Issue by rscarrasco** [maxpozdeev/mytinytodo#62]
Hi. I would like to update the existing `pt_br` language pack, but I'm not the original author. What should I put at the `author field`? Currently it is:

```
        "author": "Vitor Micillo Junior"
```

Can I include my name after the original author, like this:

```
        "author": "Vitor Micillo Junior & Rafael da Silva Carrasco"
```

or is there another way?

**Comment by maxpozdeev** [comment]
Hi!  You can set smth like:
 ```
"author": "Vitor Micillo Junior (initial), Rafael da Silva Carrasco (2023)"
```

**Comment by rscarrasco** [comment]
Ok, thanks!
