### ISSUE TITLE
Issues running through proxy

### ISSUE THREAD

**Issue by HerobrinePlayer** [maxpozdeev/mytinytodo#65]
Just setup and it is fully working when accessing directly, but running it through my reverse proxy it gives the error in the picture below.  Using the latest version downloaded from your website.

![MyTinyTodolist Proxy Issue](https://github.com/maxpozdeev/mytinytodo/assets/50325834/ad12c878-4eda-4d24-99a6-b946b40242cf)

**Comment by maxpozdeev** [comment]
I made some fixes. Please check this pre-release version.
[mytinytodo-v1.7.4-rc.tar.gz](https://github.com/maxpozdeev/mytinytodo/files/12260232/mytinytodo-v1.7.4-rc.tar.gz)

**Comment by HerobrinePlayer** [comment]
That fixed it.
