### ISSUE TITLE
Suggestion : using wttr.in in the footer

### ISSUE THREAD

**Issue by ParoTheParrot** [maxpozdeev/mytinytodo#67]
Feature request: include [wttr.in](http://wttr.in/) (https://github.com/chubin/wttr.in#one-line-output) in the footer.
I did it with sparse know-how. at the end of `includes/theme.php`:

```php
<span><?php _e('powered_by');?> 
<a href="http://www.mytinytodo.net/" class="powered-by-link">myTinyTodo</a>&nbsp;<?php mttinfo('version'); ?>
 (<?php $ch = curl_init('https://wttr.in/London?format=%c+%t,+%p'); curl_exec($ch); curl_close($ch); ?>)
</span> 
``` 

I hope for improvements, e.g. city name in settings (@maxpozdeev )!?

**Comment by maxpozdeev** [comment]
Only like an extension.

**Comment by ParoTheParrot** [comment]
Is there an instruction how to implement an extension?

**Comment by maxpozdeev** [comment]
No instructions yet.

**Comment by maxpozdeev** [comment]
Here is a quick solution. Unpack to `ext` directory, activate in settings and go to extension settings and specify URI for wattr.in url.
Also you need to edit `includes/theme.php` and add new action like in this commit c42143a17d9dc82a .

[wttrin.zip](https://github.com/maxpozdeev/mytinytodo/files/12380294/wttrin.zip)

**Comment by maxpozdeev** [comment]
In v1.8 will be `theme_footer_content_end` action which can be used to add some things to the footer.
Extension for wttr.in is above.

**Comment by ParoTheParrot** [comment]
Hi @maxpozdeev ! Just updated to 1.8.3 (works smoothly !) . With activated water plugin I see “Powered by [myTinyTodo](http://www.mytinytodo.net/) 1.8.3.      HTTP error 301” in the footer. Any ideas?
TIA!

**Comment by ParoTheParrot** [comment]
Great advice! I set the full qualified URL ( https and wttr included ).
Now it works like a charm. ✅
