### ISSUE TITLE
Near future due dates mislabeled?

### ISSUE THREAD

**Issue by Sonof8Bits** [maxpozdeev/mytinytodo#7]
Hello,

i think there's a bug with tasks set to be done tomorrow or the day after. I'll try to explain very clearly what's happening.

- Tasks due today say "today" in red.
Nothing seems off here. An expected label.
- Tasks due tomorrow say "today" in red.
Shouldn't it say "tomorrow"?
- Tasks due the day after tomorrow say "tomorrow" in red.
I think this used to be in orange and shouldn't it say "in 2 days" or something to that extend?
- Beyond that it'll switch to "in 3 days" in green.

If I remember correctly that's not how things were in an older version of MTT. Is this a bug or could something be wrong with my installation?

I'm using version 1.6.3.

**Comment by maxpozdeev** [comment]
Hi! Tasks with tomorrow duedate should be with "tomorrow" red label. Please check the timezone set in MTT settings, maybe it differs  from your local.

**Comment by Sonof8Bits** [comment]
Hallo again! The timezone seems correct. I was about to make a screenshot with test tasks for you but now it's behaving normally again, all of the sudden! :S

I'll keep an eye on it the next few days and if it happens again I'll make a screenshot and post it. And if not, I guess you can close the ticket.

**Comment by maxpozdeev** [comment]
Simple test: create a task and set it's duedate to tomorrow date. This task should change "tomorrow" label to "today" label in the midnight of the timezone you set. If not, need to investigate timezone issues.

**Comment by Sonof8Bits** [comment]
Thanks, I'll try that out later this week and get back to you.

**Comment by Sonof8Bits** [comment]
Everything seems fine now. Thanks for your time anyway!
