### ISSUE TITLE
Explicit Dark Mode

### ISSUE THREAD

**Issue by fresh2dev** [maxpozdeev/mytinytodo#70]
Settings offer "Same as system" and "Light theme", but no option for explicitly setting "Dark theme".

Dark mode works fine for me on iOS, but I am not able to activate it on my laptop running PopOS and Firefox, both configured with a dark theme.

I've resolved to manually override the CSS in "styles.css" with the colors from "dark.css", but it would be nice if this were a built-in option.

**Comment by fresh2dev** [comment]
Thank you for this enhancement, and the awesome app!

**Comment by maxpozdeev** [comment]
Just for info.
Firefox in Ubuntu 22.04 (Gnome 42) and Fedora 38 (Gnome 44) automatically switches mytinytodo v1.7 to dark theme when system appearance is changed to dark. As expected.

**Comment by maxpozdeev** [comment]
Just for info. Tested on mtt v1.7.5 in firefox 118.
In PopOS 22.04 with Gnome 42.9 firefox swtiches to dark mode automatically as expected.
In Kubuntu 22.04 with Plasma 5.24 firefox uses dark mode as expected.
No issues.
