### ISSUE TITLE
Add/Modify date doesn't work on custom short date format

### ISSUE THREAD

**Issue by stebulba** [maxpozdeev/mytinytodo#74]
All is on the title.
My setting :
![image](https://github.com/maxpozdeev/mytinytodo/assets/26193340/4553174f-c3ec-4870-adc7-fd55b244905f)

**Comment by maxpozdeev** [comment]
I can not catch this. 
What version do you use?

**Comment by stebulba** [comment]
version 1.7.6
The issue append when the custom format is probably not reconize by date() or strtotime().
n/j/y when "y" is on only two number strtotime is confuse with the order of the number.
The solution should be to convert yourself on the calendar te result with the custom date format.

**Comment by maxpozdeev** [comment]
Can you reproduce on the demo at https://mytinytodo.net/demo/ ?
It has setting of "n/j/y" for Short date format.

BTW, n/j/y should not be a custom, it is the second item to select in the dropdown list in settings.

**Comment by stebulba** [comment]
In your demo, the custom for short date format doesn't save as custom when we submit the modification.
Anyway I use on now on my localhost "j/n/Y" as custom and that work.

**Comment by maxpozdeev** [comment]
Well, I did not understand where is the error.
Will close the issue until more details are provided.

Can't repro
