### ISSUE TITLE
How can I add a new task with Telegram Bot?

### ISSUE THREAD

**Issue by MasherCoder** [maxpozdeev/mytinytodo#75]
How do I add a new task via Telegram Bot?

**Comment by maxpozdeev** [comment]
No way, only to receive notifications.

**Comment by MasherCoder** [comment]
I took care of the correspondence part with Telegram Bot, it can detect and respond to the commands I give. If I can only run a code in the form of request/query/curl, I think I will be able to add it.
For example, can we add mysite.com/mytinytodo/?add=NewTask...?

**Comment by maxpozdeev** [comment]
About external api you can read at GH-15
