### ISSUE TITLE
Notification Extension hangs

### ISSUE THREAD

**Issue by ThreshCurse** [maxpozdeev/mytinytodo#79]
Running v1.8.0

Base runs with no issues, when I enable the notifications extension to send emails the app hangs whenever I create lists/tasks. If I refresh the page the task is created. If I disable the notification extension then issue goes away.

I'm not using telegram, only trying to use the email notifications.

Are there any prerequisites for this extension?

**Comment by maxpozdeev** [comment]
Seems the app hangs while sending an email after task was created. 
Can you look at webserver/php error log for something related around your web request?
Maybe you set specific settings for php mailing functionality?

**Comment by ThreshCurse** [comment]
Thanks for getting back to me, seems that's the right direction, spinning it up on my other server works fine, they're supposed to be using the same setup so must have missed something.
