### ISSUE TITLE
Can't update from 1.6.3 to 1.8.0

### ISSUE THREAD

**Issue by vistar** [maxpozdeev/mytinytodo#85]
Error on setup.php:

```
myTinyTodo 1.8.0 Setup
Error: 'SQLSTATE[HY000]: General error: 1 no such table: mtt_settings' in setup.php:97
```

**Comment by maxpozdeev** [comment]
Thank you for reporting! Fix will be available in v1.8.1.
As for now you can replace setup.php file with new one from repository and try to upgrade again.
